routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes(['register'=> false]);


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('category', App\Http\Controllers\CategoryController::class)->middleware('auth');
Route::resource('food' , App\Http\Controllers\FoodController::class)->middleware('auth');

Route::get('/', [App\Http\Controllers\FoodController::class,'listFood']);
Route::get('/foods/{id}', [App\Http\Controllers\FoodController::class,'view'])->name('food.view');

app/Models/Category.php
<?php

namespace App\Models;

use App\Models\Food;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['name'];

    public function food(){
        return $this->hasOne(Food::class,'category_id' ,'id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::get();
        return view('category.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required',
        ]);
        Category::create([
            'name' => $request->get('name')
        ]);
        return redirect()->back()->with('message','Category created successfuly ! ');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name'=>'required',
        ]);
        $category = Category::find($id);
        $category->name = $request->get('name');
        $category->save();
        return redirect()->route('category.index')->with('message' ,'Category updated successfully !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delete();
        return redirect()->route('category.index')->with('message' ,'Category deleted successfully !');
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if(Session::has('message'))
            <div class="alert alert-success">
            {{Session::get('message')}}
            </div>
            @endif
            <form method="POST" action="{{route('category.store')}}">@csrf 
                <div class="card">
                    <div class="card-header">{{ __('Manage Food Category') }}
                    <a href="{{route('category.index')}}">
                        <button class="btn btn-outline-primary" style="margin-left: 550px;">Go to the List</button>
                    </a></div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="name">Name:</label>
                            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" >
                            @error('email')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <br>
                        <div class="form-group">
                            <button class="btn btn-outline-primary">Submit</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if(Session::has('message'))
            <div class="alert alert-success">
            {{Session::get('message')}}
            </div>
            @endif
            <form method="POST" action="{{route('category.update',[$category->id])}}">@csrf
                {{method_field('PUT')}}
                <div class="card">
                    <div class="card-header">{{ __('Update Food Category') }}</div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="name">Name:</label>
                            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{$category->name}}">
                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <br>
                        <div class="form-group">
                            <button class="btn btn-outline-primary">Update</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        	@if(Session::has('message'))
            <div class="alert alert-success">
            {{Session::get('message')}}
            </div>
            @endif
            <div class="card">
                <div class="card-header">{{ __('All Categories') }}
                	<a href="{{route('category.create')}}">
			      		<button class="btn btn-outline-primary" style="margin-left: 650px;">Create</button>
			      	</a>
                </div>

                <div class="card-body">
                   <table class="table">
					  <thead class="thead table-dark">
					    <tr>
					      <th scope="col">#</th>
					      <th scope="col">Name</th>
					      <th scope="col">Edit</th>
					      <th scope="col">Delete</th>
					    </tr>
					  </thead>
					  <tbody>
					  	@if(count($categories)>0)
					  	@foreach($categories as $key=>$category)
					    <tr>
					      <th scope="row">{{$key+1}}</th>
					      <td>{{$category->name}}</td>
					      <td>
					      	<a href="{{route('category.edit',[$category->id])}}">
					      		<button class="btn btn-outline-success">Edit</button>
					      	</a>
					      </td>
					      <td>
			      			<!-- Button trigger modal -->
							<button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal{{$category->id}}">
							  Delete
							</button>
					      	<!-- Modal -->
							<div class="modal fade" id="exampleModal{{$category->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
							  <div class="modal-dialog">
							    <div class="modal-content">
						    	<form action="{{route('category.destroy',[$category->id])}}" method="POST"> @csrf
				      			{{method_field('DELETE')}}
								      <div class="modal-header">
								        <!-- <h5 class="modal-title" id="exampleModalLabel">Modal title</h5> -->
								        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
								      </div>
								      <div class="modal-body">
								        Are you sure?
								      </div>
								      <div class="modal-footer">
								        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
								        <button type="submit" class="btn btn-outline-danger">Delete</button>
								      </div>
							      </form>
							    </div>
							  </div>
							</div>
					      </td>
					    </tr>
					    @endforeach

					    @else
					    <td>No category to display</td>
					    @endif
					  </tbody>
					</table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection