routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes(['register'=> false]);


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('category', App\Http\Controllers\CategoryController::class)->middleware('auth');
Route::resource('food' , App\Http\Controllers\FoodController::class)->middleware('auth');

Route::get('/', [App\Http\Controllers\FoodController::class,'listFood']);
Route::get('/foods/{id}', [App\Http\Controllers\FoodController::class,'view'])->name('food.view');

app/Models/Food.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Food extends Model
{
    use HasFactory;

    protected $fillable = ['name','description','price','category_id','image'];

    public function category(){
        return $this->hasOne(Category::class,'id','category_id');
    }
}

app/Http/Controllers/FoodController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Food;
use App\Models\Category;
class FoodController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $foods = Food::latest()->paginate(5);
        return view('food.index', compact('foods'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('food.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'description' => 'required',
            'price' => 'required|integer',
            'category' => 'required',
            'image'=>'required|mimes:png,jpeg,jpg',
        ]);
        $image = $request->file('image');
        $name = time(). '.' .$image->getClientOriginalExtension();
        $destinationPath = public_path('/images');
        $image->move($destinationPath, $name);        
        
        Food::create([
            'name'=> $request->get('name'),
            'description' => $request->get('description'),
            'price'=> $request->get('price'),
            'category_id'=>$request->get('category'),
            'image'=>$name,
        ]);
        return redirect()->back()->with('message','Food Created Successfuly !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $food = Food::find($id);
        return view('food.edit', compact('food'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'description' => 'required',
            'price' => 'required|integer',
            'category' => 'required',
            'image'=>'mimes:png,jpeg,jpg',
        ]);

        $food = Food::find($id);
        $name = $food->image;

        if($request->hasFile('image')){
            $image = $request->file('image');
            $name = time(). '.' .$image->getClientOriginalExtension();
            $destinationPath = public_path('/images');
            $image->move($destinationPath, $name);
        }
        $food->name = $request->get('name');
        $food->description = $request->get('description');
        $food->price = $request->get('price');
        $food->category_id = $request->get('category');
        $food->image = $name;

        $food->save();

        return redirect()->route('food.index')->with('message','Food Updatd Successfuly !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $food = Food::find($id);
        $food->delete();
        return redirect()->route('food.index')->with('message' ,'Food deleted successfully !');

    }
    public function listFood(){
        $categories = Category::with('food')->get();
        return view('index' , compact('categories'));
    }

    public function view($id){
        $food = Food::find($id);
        return view('food.detail',compact('food'));
    }
}

resources/views/food/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        	@if(Session::has('message'))
            <div class="alert alert-success">
            {{Session::get('message')}}
            </div>
            @endif
        	<form method="POST" action="{{route('food.store')}}" enctype="multipart/form-data">@csrf
            <div class="card">
                <div class="card-header">{{ __('Add New Food') }}</div>

                <div class="card-body">
                   <div class="form-group mt-3">
	                   	<label for="name">Name</label>
	                   	<input type="text" name="name" class="form-control @error('name') is-invalid @enderror"> 
	                   	@error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
						@enderror
                   </div>
                   <div class="form-group mt-3">
	                   	<label for="description">Description</label>
	                   	<textarea class="form-control @error('description') is-invalid @enderror" name="description">Description</textarea>
	                   	@error('description')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
						@enderror
                   </div>
                   <div class="form-group mt-3">
	                   	<label for="price">Price</label>
	                   	<input type="number" name="price" class="form-control @error('price') is-invalid @enderror">
	                    @error('price')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
						@enderror 

                   </div>
                   <div class="form-group mt-3">
	                   	<label for="category">Category</label>
	                   	<select name="category" class="form-control @error('category') is-invalid @enderror">
	                   		<option value="">Select Category</option>
	                   		@foreach(App\Models\Category::all() as $category)
	                   			<option value="{{$category->id}}">{{$category->name}}</option>
	                   		@endforeach
	                   	</select>
	                   	@error('category')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
						@enderror 
                   </div>
                   <div class="form-group mt-3">
	                   	<label for="image">Image</label>
	                   	<input type="file" name="image" class="form-control @error('image') is-invalid @enderror"> 
	                   	@error('image')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
						@enderror 
                   </div>
                   <div class="form-group mt-3">
	                   	<button class="btn 	btn-outline-primary">Submit</button>
                   </div>
                </div>
            </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/food/detail.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">{{ __('Image') }}</div>
                    <img src="{{asset('images')}}/{{$food->image}}" class="img-responsibe">
                <div class="card-body">
                    
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Detail') }}</div>

                <div class="card-body">
                    <p><h2>{{$food->name}}</h2></p>
                    <p class="lead">{{$food->description}}</p>
                    <p><h4>${{$food->price}}</h4></p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/food/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if(Session::has('message'))
            <div class="alert alert-success">
            {{Session::get('message')}}
            </div>
            @endif
            <form method="POST" action="{{route('food.update',[$food->id])}}" enctype="multipart/form-data">@csrf
                {{method_field('PUT')}}
                <div class="card">
                    <div class="card-header">{{ __('Update Food') }}</div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="name">Name:</label>
                            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{$food->name}}">
                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="form-group mt-3">
                        <label for="description">Description</label>
                        <textarea class="form-control @error('description') is-invalid @enderror" name="description">{{$food->description}}</textarea>
                        @error('description')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                   </div>
                   <div class="form-group mt-3">
                        <label for="price">Price</label>
                        <input type="text" name="price" class="form-control @error('price') is-invalid @enderror" value="{{$food->price}}">
                        @error('price')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror 

                   </div>
                   <div class="form-group mt-3">
                        <label for="category">Category</label>
                        <select name="category" class="form-control @error('category') is-invalid @enderror">
                            <option value="">Select Category</option>
                            @foreach(App\Models\Category::all() as $category)
                                <option value="{{$category->id}}" @if($category->id == $food->category_id) selected @endif>{{$category->name}}</option>
                            @endforeach
                        </select>
                        @error('category')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror 
                   </div>
                   <div class="form-group mt-3">
                        <label for="image">Image</label>
                        <input type="file" name="image" class="form-control @error('image') is-invalid @enderror"> 
                        @error('image')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror 
                   </div>
                        <br>
                        <div class="form-group">
                            <button class="btn btn-outline-primary">Update</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/food/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        	@if(Session::has('message'))
            <div class="alert alert-success">
            {{Session::get('message')}}
            </div>
            @endif
            <div class="card">
                <div class="card-header">{{ __('All Foods') }}
                	<a href="{{route('food.create')}}">
			      		<button class="btn btn-outline-primary" style="margin-left: 650px;">Add Food</button>
			      	</a>
                </div>

                <div class="card-body">
                   <table class="table">
					  <thead class="thead table-dark">
					    <tr>
					      <th scope="col">Image</th>
					      <th scope="col">Name</th>
					      <th scope="col">Description</th>
					      <th scope="col">Price</th>
					      <th scope="col">Category</th>
					      <th scope="col">Edit</th>
					      <th scope="col">Delete</th>
					    </tr>
					  </thead>
					  <tbody>
					  	@if(count($foods)>0)
					  	@foreach($foods as $key=>$food)
					    <tr>
					      <td><img src="{{asset('images')}}/{{$food->image}}" width="100"> </td>
					      <td>{{$food->name}}</td>
					      <td>{{$food->description}}</td>
					      <td>${{$food->price}}</td>
					      <td>{{$food->category->name}}</td>

					      <td>
					      	<a href="{{route('food.edit',[$food->id])}}">
					      		<button class="btn btn-outline-success">Edit</button>
					      	</a>
					      </td>
					      <td>
			      			<!-- Button trigger modal -->
							<button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal{{$food->id}}">
							  Delete
							</button>
					      	<!-- Modal -->
							<div class="modal fade" id="exampleModal{{$food->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
							  <div class="modal-dialog">
							    <div class="modal-content">
						    	<form action="{{route('food.destroy',[$food->id])}}" method="POST"> @csrf
				      			{{method_field('DELETE')}}
								      <div class="modal-header">
								        <!-- <h5 class="modal-title" id="exampleModalLabel">Modal title</h5> -->
								        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
								      </div>
								      <div class="modal-body">
								        Are you sure?
								      </div>
								      <div class="modal-footer">
								        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
								        <button type="submit" class="btn btn-outline-danger">Delete</button>
								      </div>
							      </form>
							    </div>
							  </div>
							</div>
					      </td>
					    </tr>
					    @endforeach

					    @else
					    <td>No food to display</td>
					    @endif
					  </tbody>
					</table>
					{{$foods->links()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection